# Author: P3TERX (Modified and Optimized)
#=================================================
name: 💻 Build OpenWrt (x86_64)
# ============================================
# 触发条件
# ============================================
on:
  workflow_dispatch:
    inputs:
      lan_addr:
        description: "📍 默认 LAN 地址"
        default: "192.168.1.10"
        required: true
        type: string
      root_password:
        description: "🔑 Root 密码"
        default: "password"
        required: false
        type: string
      docker:
        description: "🐋 Docker 支持"
        type: boolean
        default: true
      passwall:
        description: "🌐 Passwall"
        type: boolean
        default: true
      nikki:
        description: "📦 Nikki"
        type: boolean
        default: true
      openclash:
        description: "⚡ OpenClash"
        type: boolean
        default: true
      use_cache:
        description: "💾 使用缓存加速"
        type: boolean
        default: true
      debug_mode:
        description: "🐛 调试模式"
        type: boolean
        default: false
      parallel_jobs:
        description: "🔢 并行任务数 (0=自动)"
        type: string
        default: "0"
      force_clean:
        description: "🧹 强制清理缓存"
        type: boolean
        default: false
# ============================================
# 全局环境变量
# ============================================
env:
  # 源码仓库
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-24.10
  
  # 配置文件
  CONFIG_FILE: configs/x86_64.config
  DIY_SCRIPT: scripts/diy-x86_64_demo.sh
  FEEDS_CONF: feeds.conf.default
  
  # 编译设置
  CLASH_KERNEL: amd64
  CACHE_TOOLCHAIN: true
  UPLOAD_BIN_DIR: false
  FIRMWARE_RELEASE: true
  FIRMWARE_TAG: X86_64
  
  # 系统设置
  TZ: Asia/Shanghai
  DEBIAN_FRONTEND: noninteractive
# ============================================
# 并发控制
# ============================================
concurrency:
  group: build-${{ github.ref }}-${{ github.event.inputs.lan_addr }}
  cancel-in-progress: false
# ============================================
# 主任务
# ============================================
jobs:
  build:
    name: 🏗️ Build OpenWrt
    runs-on: ubuntu-24.04
    timeout-minutes: 720
    
    outputs:
      firmware_path: ${{ steps.organize.outputs.firmware_path }}
      kernel_version: ${{ steps.organize.outputs.kernel_version }}
    
    steps:
      # ============================================
      # 1. 初始化
      # ============================================
      - name: 🔧 Setup Environment
        id: env
        run: |
          # 时区设置
          sudo timedatectl set-timezone "$TZ"
          
          # Git 配置
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 生成构建信息
          VERSION=$(date +'%Y.%m.%d')
          DATE=$(date +'%Y-%m-%d %H:%M:%S')
          BUILD_ID="${{ github.run_number }}-${GITHUB_SHA::7}"
          FILE_DATE=$(date +'%Y.%m.%d-%H%M')
          TAG_TIME=$(date +'%Y.%m.%d')
          
          # 系统信息
          PROC_COUNT=$(nproc)
          MEM_GB=$(($(free -m | awk '/^Mem:/{print $2}') / 1024))
          
          # 计算并行任务数
          if [ "${{ github.event.inputs.parallel_jobs }}" = "0" ]; then
            JOBS=$((MEM_GB / 2))
            JOBS=$((JOBS > PROC_COUNT ? PROC_COUNT : JOBS))
            JOBS=$((JOBS < 1 ? 1 : JOBS))
          else
            JOBS="${{ github.event.inputs.parallel_jobs }}"
          fi
          
          # 调试模式
          if [[ "${{ github.event.inputs.debug_mode }}" == "true" ]]; then
            BUILD_FLAGS="V=s"
          else
            BUILD_FLAGS=""
          fi
          
          # 输出环境变量
          cat << EOF >> $GITHUB_ENV
          BUILD_VERSION=$VERSION
          BUILD_DATE=$DATE
          BUILD_ID=$BUILD_ID
          FILE_DATE=$FILE_DATE
          TAG_TIME=$TAG_TIME
          PROC_COUNT=$PROC_COUNT
          MEM_GB=$MEM_GB
          COMPILE_JOBS=$JOBS
          BUILD_FLAGS=$BUILD_FLAGS
          EOF
          
          # 设置缓存键
          CACHE_KEY="openwrt-${{ env.REPO_BRANCH }}-x86_64-$(date +'%Y%m')"
          echo "CACHE_KEY=$CACHE_KEY" >> $GITHUB_ENV
          
      - name: 📊 Display System Information
        run: |
          cat << EOF
          =====================================
          📊 System Information
          =====================================
          CPU Model: $(lscpu | grep 'Model name' | cut -d':' -f2 | xargs)
          CPU Cores: ${{ env.PROC_COUNT }}
          Memory: ${{ env.MEM_GB }}GB
          Compile Jobs: ${{ env.COMPILE_JOBS }}
          Kernel: $(uname -r)
          OS: $(lsb_release -ds)
          Build Version: ${{ env.BUILD_VERSION }}
          Build ID: ${{ env.BUILD_ID }}
          =====================================
          EOF
          
      # ============================================
      # 2. 磁盘空间优化
      # ============================================
      - name: 🧹 Free Disk Space
        uses: sbwml/actions@free-disk
          
      - name: 💾 Setup Swap & Memory Optimization
        run: |
          # 创建 swap
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          
          # 优化内存管理
          cat << EOF | sudo tee -a /etc/sysctl.conf
          vm.swappiness=10
          vm.vfs_cache_pressure=50
          vm.dirty_ratio=15
          vm.dirty_background_ratio=5
          vm.max_map_count=262144
          EOF
          sudo sysctl -p
          
          echo "Memory status:"
          free -h
      
      # ============================================
      # 3. 代码检出
      # ============================================
      - name: ✅ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
              
      # ============================================
      # 4. 多层缓存策略
      # ============================================
      - name: 💾 Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            /opt/hostedtoolcache
            ~/.cache/pip
            ~/.npm
          key: deps-${{ runner.os }}-${{ hashFiles('**/package*.json', '**/requirements*.txt') }}
          restore-keys: |
            deps-${{ runner.os }}-
            
      - name: 💾 Cache OpenWrt Source
        id: cache-source
        uses: actions/cache@v4
        with:
          path: openwrt
          key: source-${{ env.CACHE_KEY }}-${{ hashFiles('.github/workflows/*.yml', 'configs/*.config') }}
          restore-keys: |
            source-${{ env.CACHE_KEY }}-
            source-openwrt-${{ env.REPO_BRANCH }}-
            
      - name: 💾 Cache Downloads
        uses: actions/cache@v4
        with:
          path: openwrt/dl
          key: downloads-${{ env.CACHE_KEY }}-${{ hashFiles('configs/*.config') }}
          restore-keys: |
            downloads-${{ env.CACHE_KEY }}-
            downloads-openwrt-${{ env.REPO_BRANCH }}-
            
      - name: 💾 Cache Toolchain
        if: github.event.inputs.use_cache == 'true'
        uses: actions/cache@v4
        with:
          path: |
            openwrt/staging_dir/toolchain-*
            openwrt/staging_dir/host
            openwrt/build_dir/host
          key: toolchain-${{ env.CACHE_KEY }}-${{ hashFiles('configs/*.config') }}
          restore-keys: |
            toolchain-${{ env.CACHE_KEY }}-
            toolchain-openwrt-${{ env.REPO_BRANCH }}-
            
      - name: 💾 Cache Build Directory
        if: github.event.inputs.use_cache == 'true'
        uses: actions/cache@v4
        with:
          path: |
            openwrt/build_dir/target-*
            openwrt/.ccache
          key: build-${{ env.CACHE_KEY }}-${{ hashFiles('configs/*.config') }}-${{ github.sha }}
          restore-keys: |
            build-${{ env.CACHE_KEY }}-${{ hashFiles('configs/*.config') }}-
            build-${{ env.CACHE_KEY }}-
            
      # ============================================
      # 5. 环境安装
      # ============================================
      - name: Build System Setup
        uses: sbwml/actions@openwrt-build-setup
            
      - name: 📦 Install LLVM
        uses: sbwml/actions@install-llvm
        
      # ============================================
      # 6. 源码处理
      # ============================================
      - name: 📥 Prepare OpenWrt Source
        run: |
          if [ ! -d "openwrt" ] || [ "${{ github.event.inputs.force_clean }}" = "true" ]; then
            echo "🔄 Cloning OpenWrt source..."
            rm -rf openwrt
            git clone --depth=1 "$REPO_URL" -b "$REPO_BRANCH" openwrt
          else
            echo "✅ Using cached OpenWrt source"
            cd openwrt
            git fetch --depth=1 origin $REPO_BRANCH
            git reset --hard FETCH_HEAD
            git clean -fd
          fi
          
          cd openwrt
          echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
          
          # 获取提交信息
          COMMIT_INFO=$(git log -1 --pretty=format:'%an|%ci|%s|%H')
          IFS='|' read -r AUTHOR DATE MESSAGE HASH <<< "$COMMIT_INFO"
          
          cat << EOF >> $GITHUB_ENV
          COMMIT_AUTHOR=$AUTHOR
          COMMIT_DATE=$DATE
          COMMIT_MESSAGE=$MESSAGE
          COMMIT_HASH=$HASH
          EOF
          
      # ============================================
      # 7. Feeds 配置
      # ============================================
      - name: 📚 Configure Feeds
        run: |
          cd $OPENWRT_PATH
          
          # 复制 feeds 配置
          if [ -f "${{ github.workspace }}/feeds.conf.default" ]; then
            cp ${{ github.workspace }}/feeds.conf.default .
          fi
          
          # 更新 feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      # ============================================
      # 8. 自定义配置
      # ============================================
      - name: 🎨 Apply Custom Configuration
        env:
          LAN: ${{ github.event.inputs.lan_addr }}
          ROOT_PASSWORD: ${{ github.event.inputs.root_password }}
          ENABLE_DOCKER: ${{ github.event.inputs.docker }}
          ENABLE_SSRP: ${{ github.event.inputs.ssrp }}
          ENABLE_PASSWALL: ${{ github.event.inputs.passwall }}
          ENABLE_NIKKI: ${{ github.event.inputs.nikki }}
          ENABLE_OPENCLASH: ${{ github.event.inputs.openclash }}
        run: |
          cd $OPENWRT_PATH
          
          # 复制自定义文件
          [ -e ${{ github.workspace }}/files ] && cp -r ${{ github.workspace }}/files .
          
          # 复制配置文件
          cp ${{ github.workspace }}/${CONFIG_FILE} .config
          
          # 执行自定义脚本
          chmod +x ${{ github.workspace }}/scripts/*.sh
          chmod +x ${{ github.workspace }}/$DIY_SCRIPT
          
          ${{ github.workspace }}/$DIY_SCRIPT
          ${{ github.workspace }}/scripts/preset-mihimo-core.sh $CLASH_KERNEL
          ${{ github.workspace }}/scripts/preset-adguard-core.sh $CLASH_KERNEL
          
          # 生成最终配置
          make defconfig
          
          # 提取设备信息
          DEVICE_TARGET=$(grep '^CONFIG_TARGET_BOARD=' .config | cut -d'"' -f2)
          DEVICE_SUBTARGET=$(grep '^CONFIG_TARGET_SUBTARGET=' .config | cut -d'"' -f2)
          
          echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
          echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
          
      # ============================================
      # 9. 清理构建目录（如果需要）
      # ============================================
      - name: 🧹 Clean Build Directory
        if: github.event.inputs.force_clean == 'true'
        run: |
          cd $OPENWRT_PATH
          echo "🧹 Force cleaning build directory..."
          make dirclean
          make defconfig
          
      # ============================================
      # 10. 下载依赖包
      # ============================================
      - name: 📥 Download Packages
        run: |
          cd $OPENWRT_PATH
          
          echo "📥 Downloading packages..."
          make download -j$((COMPILE_JOBS + 1))
          
          # 检查并重试失败的下载
          FAILED_COUNT=$(find dl -size -1024c | wc -l)
          if [ $FAILED_COUNT -gt 0 ]; then
            echo "⚠️ Found $FAILED_COUNT failed downloads, retrying..."
            find dl -size -1024c -delete
            make download -j1 V=s
          fi
          
          echo "✅ Package download completed"
          
      # ============================================
      # 11. 编译固件
      # ============================================
      - name: 🔨 Compile Firmware
        id: compile
        timeout-minutes: 600
        run: |
          cd $OPENWRT_PATH
          
          # 启用 ccache
          export USE_CCACHE=1
          export CCACHE_DIR=$PWD/.ccache
          ccache -M 5G
          ccache -s
          
          echo "🔨 Starting compilation with $COMPILE_JOBS jobs..."
          
          # 渐进式编译策略
          compile_with_jobs() {
            local jobs=$1
            echo "🔧 Attempting compilation with $jobs jobs..."
            if make -j$jobs $BUILD_FLAGS; then
              echo "✅ Compilation successful with $jobs jobs"
              return 0
            else
              echo "❌ Compilation failed with $jobs jobs"
              return 1
            fi
          }
          
          # 尝试不同的并行度
          if compile_with_jobs $COMPILE_JOBS; then
            SUCCESS=true
          elif compile_with_jobs $((COMPILE_JOBS/2)); then
            SUCCESS=true
          elif compile_with_jobs 1; then
            SUCCESS=true
          else
            echo "❌ All compilation attempts failed"
            
            # 输出详细错误信息
            echo "=== Build log tail ==="
            tail -n 50 build.log 2>/dev/null || echo "No build log found"
            
            echo "=== Failed packages ==="
            find logs -name "*.log" -exec echo "=== {} ===" \; -exec tail -n 20 {} \; 2>/dev/null || true
            
            exit 1
          fi
          
          # 显示 ccache 统计
          ccache -s
          
          echo "status=success" >> $GITHUB_OUTPUT
          
      # ============================================
      # 12. 整理固件文件
      # ============================================
      - name: 📦 Organize Firmware
        if: steps.compile.outputs.status == 'success'
        id: organize
        run: |
          cd $OPENWRT_PATH/bin/targets/*/*
          
          echo "=== Generated files ==="
          ls -lah
          
          # 提取内核版本
          KERNEL_VERSION=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')
          
          # 保存配置文件
          cp $OPENWRT_PATH/.config build.config
          
          # 压缩内核模块
          if [ -d packages ]; then
            tar -czf kernel-modules.tar.gz packages/
            rm -rf packages
          fi
          
          # 清理不必要的文件
          rm -f feeds.buildinfo version.buildinfo
          
          # 生成固件信息文件
          cat > firmware_info.json << EOF
          {
            "build_date": "$BUILD_DATE",
            "build_version": "$BUILD_VERSION",
            "build_id": "$BUILD_ID",
            "kernel_version": "$KERNEL_VERSION",
            "target": "$DEVICE_TARGET",
            "subtarget": "$DEVICE_SUBTARGET",
            "lan_address": "${{ github.event.inputs.lan_addr }}",
            "commit_hash": "$COMMIT_HASH",
            "plugins": {
              "docker": ${{ github.event.inputs.docker }},
              "ssrp": ${{ github.event.inputs.ssrp }},
              "passwall": ${{ github.event.inputs.passwall }},
              "openclash": ${{ github.event.inputs.openclash }},
              "nikki": ${{ github.event.inputs.nikki }}
            }
          }
          EOF
          
          echo "firmware_path=$PWD" >> $GITHUB_OUTPUT
          echo "kernel_version=$KERNEL_VERSION" >> $GITHUB_OUTPUT
          echo "KERNEL_VERSION=$KERNEL_VERSION" >> $GITHUB_ENV
          echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
          
      # ============================================
      # 13. 上传 Artifacts
      # ============================================
      - name: 📤 Upload Firmware
        if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt-${{ env.DEVICE_TARGET }}-${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE_PATH }}
          retention-days: 30
          compression-level: 6
          
      # ============================================
      # 14. 创建 Release
      # ============================================
      - name: 🚀 Create Release
        if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE == 'true'
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.FILE_DATE }}-OpenWrt-${{ env.FIRMWARE_TAG }}
          tag: ${{ env.FIRMWARE_TAG }}-${{ env.BUILD_VERSION }}
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.FIRMWARE_PATH }}/*
          body: |
            ## 🎯 OpenWrt Firmware [${{ env.BUILD_ID }}]
            
            ### 📊 构建信息
            | 项目 | 信息 |
            |------|------|
            | **版本** | `${{ env.BUILD_VERSION }}` |
            | **日期** | `${{ env.BUILD_DATE }}` |
            | **目标** | `${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}` |
            | **内核** | `${{ env.KERNEL_VERSION }}` |
            | **LAN IP** | `${{ github.event.inputs.lan_addr }}` |
            | **密码** | `${{ github.event.inputs.root_password }}` |
            
            ### 📦 包含的插件
            | 插件 | 状态 |
            |------|------|
            | Docker | ${{ github.event.inputs.docker == 'true' && '✅ 已启用' || '❌ 未启用' }} |
            | ShadowSocksR Plus+ | ${{ github.event.inputs.ssrp == 'true' && '✅ 已启用' || '❌ 未启用' }} |
            | Passwall | ${{ github.event.inputs.passwall == 'true' && '✅ 已启用' || '❌ 未启用' }} |
            | OpenClash | ${{ github.event.inputs.openclash == 'true' && '✅ 已启用' || '❌ 未启用' }} |
            | Nikki | ${{ github.event.inputs.nikki == 'true' && '✅ 已启用' || '❌ 未启用' }} |
            
            ### 📝 源码信息
            - **仓库**: [${{ env.REPO_URL }}](${{ env.REPO_URL }})
            - **分支**: `${{ env.REPO_BRANCH }}`
            - **提交**: `${{ env.COMMIT_HASH }}`
            - **作者**: ${{ env.COMMIT_AUTHOR }}
            - **时间**: ${{ env.COMMIT_DATE }}
            - **消息**: ${{ env.COMMIT_MESSAGE }}
            
            ### 📥 安装说明
            ```bash
            # 解压固件
            gunzip openwrt-*.img.gz
            
            # 写入设备
            dd if=openwrt-*.img of=/dev/sdX bs=4M status=progress
